// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxlgcbkxraytmsiaflgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bGdjYmt4cmF5dG1zaWFmbGd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MzU1ODQsImV4cCI6MjA2NTExMTU4NH0.U8snwALYcIBDIGuscV09OPrcExp8AFzDwPDP-DryB0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);